apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-hash
template:
  metadata:
    labels:
      app: fastapi-hash
spec:
  containers:
  - name: app
  image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/fastapi-hash:latest
  ports:
  - containerPort: 8000
  env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: DATABASE_URL
