apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-hash
  template:
    metadata:
      labels:
        app: fastapi-hash
    spec:
      containers:
      - name: app
        image: 688933601318.dkr.ecr.us-east-2.amazonaws.com/fastapi-hash:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://hashuser:changeme123@hash-service-postgres.cfum8aocuvri.us-east-2.rds.amazonaws.com:5432/hashdb