apiVersion: v1
kind: Service
metadata:
  name: hash-app-svc
  namespace: hash-app
spec:
  type: LoadBalancer
  selector:
    app: hash-app
  ports:
    - port: 80        # Public port
      targetPort: 8080

